name: appuasd
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  webview_flutter: ^4.0.0
  video_player: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo2.png
    - assets/yop.jpg
    - assets/uasd.png
    - assets/seleccion.jpg
    - assets/insittucional.jpg
    - assets/seleccion.mp4
    - assets/institucional.mp4
